-- Run this in Supabase Dashboard > SQL Editor.
-- Creates the notifications and audit_logs tables used by the admin pages,
-- with RLS policies so staff/admin can read them and users can manage
-- their own notifications.

-- ============================================================
-- NOTIFICATIONS
-- ============================================================
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  type text not null default 'info' check (type in ('urgent', 'info', 'warning', 'error')),
  user_id uuid references auth.users(id) on delete cascade,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.notifications enable row level security;

-- Reset every notification policy first. This also recovers cleanly from
-- earlier setup runs that created a policy before being interrupted.
do $$
declare
  existing_policy record;
begin
  for existing_policy in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'notifications'
  loop
    execute format('drop policy if exists %I on public.notifications', existing_policy.policyname);
  end loop;
end;
$$;

-- Staff/admin can read all notifications.
create policy "Staff can read all notifications"
on public.notifications
for select
to authenticated
using ((select public.is_tfro_staff()));

-- Users can read notifications addressed to them.
create policy "Users can read their own notifications"
on public.notifications
for select
to authenticated
using ((user_id is null) or (user_id = (select auth.uid())));

-- Users can mark their own notifications as read.
create policy "Users can update their own notifications"
on public.notifications
for update
to authenticated
using ((user_id = (select auth.uid())) or (user_id is null and (select public.is_tfro_staff())))
with check ((user_id = (select auth.uid())) or (user_id is null and (select public.is_tfro_staff())));

-- Users can delete their own notifications.
create policy "Users can delete their own notifications"
on public.notifications
for delete
to authenticated
using ((user_id = (select auth.uid())) or (user_id is null and (select public.is_tfro_staff())));

-- Staff/admin can create notifications.
create policy "Staff can create notifications"
on public.notifications
for insert
to authenticated
with check ((select public.is_tfro_staff()));

-- Seed sample notifications (safe to run repeatedly).
-- NOTE: user_id is uuid, so all NULLs must be cast to uuid explicitly.
insert into public.notifications (title, message, type, user_id, is_read)
select * from (values
  ('Franchise Expiring Soon', 'FR-2024-0451 — Ernesto Bautista expires in 3 days.', 'urgent', null::uuid, false),
  ('Franchise Expiring Soon', 'FR-2024-0388 — Mario Villanueva expires in 7 days.', 'urgent', null::uuid, false),
  ('Pending Application', 'New franchise application FR-2024-0892 from Roberto Dela Cruz awaits review.', 'info', null::uuid, false),
  ('Unpaid Penalty', 'Eduardo Reyes has an unpaid penalty of ₱300.', 'warning', null::uuid, true),
  ('Franchise Expired', 'FR-2023-0447 — Luis Magno has officially expired.', 'error', null::uuid, true)
) as seed(title, message, type, user_id, is_read)
where not exists (select 1 from public.notifications);

-- ============================================================
-- AUDIT LOGS
-- ============================================================
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_name text,
  role text,
  action text not null,
  action_type text,
  ip_address text,
  created_at timestamptz not null default now()
);

alter table public.audit_logs enable row level security;

-- Make this script safe to re-run: drop existing policies first.
drop policy if exists "Staff can read audit logs" on public.audit_logs;
drop policy if exists "Users can insert audit logs" on public.audit_logs;

-- Staff/admin can read all audit logs.
create policy "Staff can read audit logs"
on public.audit_logs
for select
to authenticated
using ((select public.is_tfro_staff()));

-- Users can insert audit log entries (e.g., login, profile update).
create policy "Users can insert audit logs"
on public.audit_logs
for insert
to authenticated
with check (true);

-- Seed a few sample audit log entries.
insert into public.audit_logs (user_name, role, action, action_type, ip_address, created_at)
select * from (values
  ('Maria Santos', 'admin', 'Approved franchise FR-2024-0891', 'approval', '192.168.1.10', now() - interval '2 hours'),
  ('Jose Reyes', 'staff', 'Recorded violation for Ricardo Lim', 'violation', '192.168.1.12', now() - interval '5 hours'),
  ('Antonio Cruz', 'operator', 'Logged in to system', 'login', '192.168.1.25', now() - interval '1 day')
) as seed(user_name, role, action, action_type, ip_address, created_at)
where not exists (select 1 from public.audit_logs);

grant execute on function public.is_tfro_staff() to authenticated;

