-- Run this in Supabase Dashboard > SQL Editor after setup-auth.sql.
create table if not exists public.franchises (
  id bigint generated by default as identity primary key,
  franchise_number text not null unique,
  operator_name text not null,
  route text not null,
  status text not null default 'pending' check (status in ('active', 'pending', 'expired', 'suspended')),
  application_type text not null default 'new' check (application_type in ('new', 'renewal')),
  application_date date not null default current_date,
  expiration_date date,
  created_at timestamptz not null default now()
);

create table if not exists public.violations (
  id bigint generated by default as identity primary key,
  violation_type text not null,
  description text,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  amount numeric(12, 2) not null check (amount >= 0),
  paid_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create or replace function public.is_tfro_staff()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'staff')); $$;

grant execute on function public.is_tfro_staff() to authenticated;

alter table public.franchises enable row level security;
alter table public.violations enable row level security;
alter table public.payments enable row level security;

create policy "Staff can read franchises" on public.franchises for select to authenticated using ((select public.is_tfro_staff()));
create policy "Staff can read violations" on public.violations for select to authenticated using ((select public.is_tfro_staff()));
create policy "Staff can read payments" on public.payments for select to authenticated using ((select public.is_tfro_staff()));
