-- ============================================================================
-- TFRO-MIS Integrated Workflow Schema
-- Connects Admin, Operator Portal, Driver Portal and Franchise Management
-- into one system using foreign keys (not names).
-- Run this ONCE in Supabase Dashboard > SQL Editor after the existing scripts.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Link existing "operators" to the auth.profiles user account
-- ---------------------------------------------------------------------------
alter table public.operators add column if not exists user_id uuid references public.profiles(id) on delete set null;
alter table public.operators add column if not exists verified boolean not null default false;

-- ---------------------------------------------------------------------------
-- Link existing "franchises" to the operator profile + originating application.
-- NOTE: operator_id is added here (BEFORE the RLS policies below) because the
-- TRICYCLE and CHANGE MOTOR HISTORY policies reference franchises.operator_id.
-- ---------------------------------------------------------------------------
alter table public.franchises add column if not exists operator_id uuid references public.profiles(id) on delete set null;

-- ---------------------------------------------------------------------------
-- Link existing "drivers" to the auth.profiles user account + license fields
-- ---------------------------------------------------------------------------
alter table public.drivers add column if not exists user_id uuid references public.profiles(id) on delete set null;
alter table public.drivers add column if not exists franchise_id bigint references public.franchises(id) on delete set null;
alter table public.drivers add column if not exists operator_id bigint references public.operators(id) on delete set null;
alter table public.drivers add column if not exists address text;
alter table public.drivers add column if not exists license_type text;
alter table public.drivers add column if not exists license_expiration date;
alter table public.drivers
  add column if not exists license_status text not null default 'not_verified'
  check (license_status in ('verified', 'not_verified', 'expired'));
alter table public.drivers add column if not exists license_verified_at timestamptz;

-- ---------------------------------------------------------------------------
-- FRANCHISE APPLICATIONS (Operator submits -> Admin reviews)
-- Does NOT automatically create a franchise record.
-- ---------------------------------------------------------------------------
create table if not exists public.franchise_applications (
  id bigint generated by default as identity primary key,
  operator_id uuid not null references public.profiles(id) on delete cascade,
  application_code text,
  franchise_number text,
  previous_registration text,
  operator_name text,
  registration_month integer,
  registration_day integer,
  registration_year integer,
  address text,
  engine_number text,
  chassis_number text,
  plate_number text,
  contact_number text,
  route text,
  status text not null default 'pending_review'
    check (status in ('pending_review', 'reviewing', 'approved', 'rejected', 'needs_correction')),
  -- Admin review / approval
  admin_id uuid references public.profiles(id) on delete set null,
  admin_name text,
  admin_approved_at timestamptz,
  -- Review checklist
  info_complete boolean not null default false,
  -- Document verification flags
  voters_verified boolean not null default false,
  barangay_verified boolean not null default false,
  cedula_verified boolean not null default false,
  ohcr_verified boolean not null default false,
  insurance_verified boolean not null default false,
  pmbl_verified boolean not null default false,
  -- Rejection
  rejection_reason text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- FRANCHISE DOCUMENTS (one row per required PDF per application)
-- doc_type: voters, barangay, cedula, ohcr, insurance, pmbl
-- ---------------------------------------------------------------------------
create table if not exists public.franchise_documents (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.franchise_applications(id) on delete cascade,
  doc_type text not null
    check (doc_type in ('voters', 'barangay', 'cedula', 'ohcr', 'insurance', 'pmbl')),
  file_name text not null,
  storage_path text not null,
  file_size integer not null default 0,
  verified boolean not null default false,
  status text not null default 'pending' check (status in ('pending', 'verified', 'needs_correction')),
  admin_note text,
  uploaded_at timestamptz not null default now(),
  unique (application_id, doc_type)
);

-- ---------------------------------------------------------------------------
-- TRICYCLES (one per approved franchise)
-- ---------------------------------------------------------------------------
create table if not exists public.tricycles (
  id bigint generated by default as identity primary key,
  franchise_id bigint not null references public.franchises(id) on delete cascade,
  engine_number text,
  chassis_number text,
  plate_number text,
  motor_brand text,
  motor_serial text,
  is_current boolean not null default true,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- CHANGE MOTOR / MTOP HISTORY (preserve old vehicle info)
-- ---------------------------------------------------------------------------
create table if not exists public.change_motor_history (
  id bigint generated by default as identity primary key,
  franchise_id bigint not null references public.franchises(id) on delete cascade,
  old_engine_number text,
  old_chassis_number text,
  old_plate_number text,
  new_engine_number text,
  new_chassis_number text,
  new_plate_number text,
  changed_by uuid references public.profiles(id) on delete set null,
  changed_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- CHANGE MOTOR REQUESTS (Operator requests -> Admin approves)
-- ---------------------------------------------------------------------------
create table if not exists public.change_motor_requests (
  id bigint generated by default as identity primary key,
  operator_id uuid not null references public.profiles(id) on delete cascade,
  franchise_id bigint references public.franchises(id) on delete set null,
  request_code text,
  -- current vehicle
  old_engine_number text,
  old_chassis_number text,
  old_plate_number text,
  -- new vehicle
  new_engine_number text,
  new_chassis_number text,
  new_plate_number text,
  new_motor_brand text,
  new_motor_serial text,
  supporting_file_name text,
  supporting_storage_path text,
  status text not null default 'pending_review'
    check (status in ('pending_review', 'reviewing', 'approved', 'rejected')),
  admin_id uuid references public.profiles(id) on delete set null,
  admin_name text,
  admin_reviewed_at timestamptz,
  rejection_reason text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- DRIVER ASSIGNMENTS (links a driver to an operator/franchise)
-- ---------------------------------------------------------------------------
create table if not exists public.driver_assignments (
  id bigint generated by default as identity primary key,
  driver_id bigint not null references public.drivers(id) on delete cascade,
  driver_user_id uuid references public.profiles(id) on delete set null,
  operator_id bigint references public.operators(id) on delete set null,
  operator_user_id uuid references public.profiles(id) on delete set null,
  franchise_id bigint references public.franchises(id) on delete set null,
  status text not null default 'active' check (status in ('active', 'inactive')),
  assigned_at timestamptz not null default now(),
  unique (driver_id, franchise_id)
);

-- ---------------------------------------------------------------------------
-- NOTIFICATIONS (per user)
-- ---------------------------------------------------------------------------
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text,
  message text not null,
  link text,
  type text not null default 'info' check (type in ('urgent', 'info', 'warning', 'error', 'success')),
  user_id uuid references public.profiles(id) on delete cascade,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- AUDIT: reusable helper to find the current user's role
-- ---------------------------------------------------------------------------
create or replace function public.current_role()
returns text language sql stable security definer set search_path = public
as $$ select role from public.profiles where id = auth.uid(); $$;

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

-- OPERATORS: staff manage all; an operator reads their own row
alter table public.operators force row level security;
drop policy if exists "Staff manage operators" on public.operators;
create policy "Staff manage operators" on public.operators
  for all to authenticated using (public.is_tfro_staff()) with check (public.is_tfro_staff());
drop policy if exists "Operator read own" on public.operators;
create policy "Operator read own" on public.operators
  for select to authenticated using (user_id = auth.uid());

-- DRIVERS: staff manage all; a driver reads their own row
alter table public.drivers force row level security;
drop policy if exists "Staff manage drivers" on public.drivers;
create policy "Staff manage drivers" on public.drivers
  for all to authenticated using (public.is_tfro_staff()) with check (public.is_tfro_staff());
drop policy if exists "Driver read own" on public.drivers;
create policy "Driver read own" on public.drivers
  for select to authenticated using (user_id = auth.uid());

-- FRANCHISE APPLICATIONS
alter table public.franchise_applications force row level security;
drop policy if exists "Staff all applications" on public.franchise_applications;
create policy "Staff all applications" on public.franchise_applications
  for all to authenticated using (public.is_tfro_staff()) with check (public.is_tfro_staff());
drop policy if exists "Operator own applications" on public.franchise_applications;
create policy "Operator own applications" on public.franchise_applications
  for select to authenticated using (operator_id = auth.uid());
drop policy if exists "Operator insert application" on public.franchise_applications;
create policy "Operator insert application" on public.franchise_applications
  for insert to authenticated with check (operator_id = auth.uid());
drop policy if exists "Operator update own application" on public.franchise_applications;
create policy "Operator update own application" on public.franchise_applications
  for update to authenticated using (operator_id = auth.uid()) with check (operator_id = auth.uid());

-- FRANCHISE DOCUMENTS
alter table public.franchise_documents force row level security;
drop policy if exists "Staff all documents" on public.franchise_documents;
create policy "Staff all documents" on public.franchise_documents
  for all to authenticated using (public.is_tfro_staff()) with check (public.is_tfro_staff());
drop policy if exists "Operator own documents" on public.franchise_documents;
create policy "Operator own documents" on public.franchise_documents
  for select to authenticated using (
    exists (select 1 from public.franchise_applications a
            where a.id = application_id and a.operator_id = auth.uid())
  );
drop policy if exists "Operator insert documents" on public.franchise_documents;
create policy "Operator insert documents" on public.franchise_documents
  for insert to authenticated with check (
    exists (select 1 from public.franchise_applications a
            where a.id = application_id and a.operator_id = auth.uid())
  );
drop policy if exists "Operator update documents" on public.franchise_documents;
create policy "Operator update documents" on public.franchise_documents
  for update to authenticated using (
    exists (select 1 from public.franchise_applications a
            where a.id = application_id and a.operator_id = auth.uid())
  ) with check (
    exists (select 1 from public.franchise_applications a
            where a.id = application_id and a.operator_id = auth.uid())
  );

-- TRICYCLES
alter table public.tricycles force row level security;
drop policy if exists "Staff all tricycles" on public.tricycles;
create policy "Staff all tricycles" on public.tricycles
  for all to authenticated using (public.is_tfro_staff()) with check (public.is_tfro_staff());
drop policy if exists "Operator read own tricycle" on public.tricycles;
create policy "Operator read own tricycle" on public.tricycles
  for select to authenticated using (
    exists (select 1 from public.franchises f
            where f.id = franchise_id and f.operator_id = auth.uid())
  );

-- CHANGE MOTOR REQUESTS
alter table public.change_motor_requests force row level security;
drop policy if exists "Staff all change motor" on public.change_motor_requests;
create policy "Staff all change motor" on public.change_motor_requests
  for all to authenticated using (public.is_tfro_staff()) with check (public.is_tfro_staff());
drop policy if exists "Operator own change motor" on public.change_motor_requests;
create policy "Operator own change motor" on public.change_motor_requests
  for select to authenticated using (operator_id = auth.uid());
drop policy if exists "Operator insert change motor" on public.change_motor_requests;
create policy "Operator insert change motor" on public.change_motor_requests
  for insert to authenticated with check (operator_id = auth.uid());

-- CHANGE MOTOR HISTORY
alter table public.change_motor_history force row level security;
drop policy if exists "Staff all history" on public.change_motor_history;
create policy "Staff all history" on public.change_motor_history
  for all to authenticated using (public.is_tfro_staff()) with check (public.is_tfro_staff());
drop policy if exists "Operator read history" on public.change_motor_history;
create policy "Operator read history" on public.change_motor_history
  for select to authenticated using (
    exists (select 1 from public.franchises f
            where f.id = franchise_id and f.operator_id = auth.uid())
  );

-- DRIVER ASSIGNMENTS
alter table public.driver_assignments force row level security;
drop policy if exists "Staff all assignments" on public.driver_assignments;
create policy "Staff all assignments" on public.driver_assignments
  for all to authenticated using (public.is_tfro_staff()) with check (public.is_tfro_staff());
drop policy if exists "Operator read assignment" on public.driver_assignments;
create policy "Operator read assignment" on public.driver_assignments
  for select to authenticated using (operator_user_id = auth.uid());
drop policy if exists "Driver read assignment" on public.driver_assignments;
create policy "Driver read assignment" on public.driver_assignments
  for select to authenticated using (driver_user_id = auth.uid());

-- NOTIFICATIONS
alter table public.notifications force row level security;
drop policy if exists "User read notifications" on public.notifications;
create policy "User read notifications" on public.notifications
  for select to authenticated using (user_id = auth.uid());
drop policy if exists "User insert notification" on public.notifications;
create policy "User insert notification" on public.notifications
  for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "System insert notification" on public.notifications;
create policy "System insert notification" on public.notifications
  for insert to authenticated with check (true);

-- Link the application that this franchise was created from
alter table public.franchises add column if not exists application_id bigint references public.franchise_applications(id) on delete set null;

-- Reload PostgREST schema cache
notify pgrst, 'reload schema';
