-- Run once after setup-dashboard.sql.
create table if not exists public.operators (
  id bigint generated by default as identity primary key,
  full_name text not null,
  address text not null,
  contact_number text not null,
  franchise_number text,
  status text not null default 'active' check (status in ('active', 'inactive', 'suspended')),
  created_at timestamptz not null default now()
);

alter table public.operators enable row level security;
drop policy if exists "Staff can manage operators" on public.operators;
create policy "Staff can manage operators"
on public.operators for all to authenticated
using ((select public.is_tfro_staff()))
with check ((select public.is_tfro_staff()));
