-- Run once after setup-dashboard.sql.
create table if not exists public.drivers (
  id bigint generated by default as identity primary key,
  full_name text not null,
  license_number text not null unique,
  operator_name text not null,
  contact_number text not null,
  violation_count integer not null default 0 check (violation_count >= 0),
  compliance text not null default 'compliant' check (compliance in ('compliant', 'non-compliant')),
  created_at timestamptz not null default now()
);

alter table public.drivers enable row level security;
create policy "Staff can manage drivers"
on public.drivers for all to authenticated
using ((select public.is_tfro_staff()))
with check ((select public.is_tfro_staff()));
