import { supabase } from "./supabase.js";
import { requireRole } from "./auth-guard.js";
import { logAudit } from "./audit-helper.js";

let payments = [], pendingViolations = [], currentUserId = null, currentRole = null;
const table = document.getElementById("paymentsTable"), modal = document.getElementById("paymentModal"), form = document.getElementById("paymentForm");
const peso = (amount) => "₱" + Number(amount || 0).toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#039;", '"':"&quot;" })[char]);
const normalize = (payment) => ({ ...payment, receipt:payment.receipt || `LEGACY-${payment.id}`, payer:payment.payer || "Unknown payer", type:payment.payment_type || "Penalty", status:payment.status || "paid", date:payment.paid_at ? String(payment.paid_at).slice(0,10) : "—" });

async function verifyAccess() {
  const { user, profile } = await requireRole(["staff", "admin"]);
  currentUserId = user?.id || null; currentRole = profile?.role || null;
  document.getElementById("recordPaymentBtn").hidden = currentRole !== "staff";
  document.querySelector(".topbar h1").textContent = currentRole === "admin" ? "Administrator — Payment & Release Records" : "TFRO Staff / PAYA — Violation Payments";
  return Boolean(user);
}

function render(rows) {
  table.innerHTML = rows.length ? rows.map((payment) => { const violation = payment.violations || {}; return `<tr><td>${escapeHtml(payment.receipt)}</td><td>${escapeHtml(payment.payer)}</td><td><span class="type penalty">${escapeHtml(payment.type)}</span></td><td>${escapeHtml(violation.classification || "—")}</td><td>${peso(violation.discounted)}</td><td>${peso(payment.amount)}</td><td>${escapeHtml(payment.date)}</td><td><span class="status ${escapeHtml(payment.status)}">${escapeHtml(payment.status)}</span></td><td><div class="actions"><button type="button" data-action="order" data-id="${payment.id}" title="View/download TFRO-009"><i class="ri-file-pdf-2-line"></i> 009</button><button type="button" data-action="release" data-id="${payment.id}" title="View/download TFRO-010"><i class="ri-file-pdf-2-line"></i> 010</button>${violation.treasurer_receipt_path ? `<button type="button" data-action="proof" data-id="${payment.id}" title="View City Treasurer receipt"><i class="ri-image-line"></i></button>` : ""}</div></td></tr>`; }).join("") : '<tr><td colspan="9">No payments recorded.</td></tr>';
}
function applyFilters() { const term=document.getElementById("searchInput").value.trim().toLowerCase(), status=document.getElementById("statusFilter").value; render(payments.filter((payment)=>(status==="all"||payment.status===status)&&`${payment.payer} ${payment.receipt} ${payment.violations?.ticket_number||""}`.toLowerCase().includes(term))); }
function updateTotals() { const collected=payments.filter((p)=>p.status==="paid").reduce((sum,p)=>sum+Number(p.amount),0); document.getElementById("totalCollected").textContent=peso(collected); document.getElementById("apprehenderShare").textContent=peso(collected*.2); document.getElementById("pendingCount").textContent=pendingViolations.length; document.getElementById("overdueCount").textContent=payments.filter((p)=>p.status==="overdue").length; }

async function loadPayments() {
  const paymentFields="id,receipt,payer,payment_type,amount,status,paid_at,violation_id,receipt_snapshot,unit_owner_name,unit_owner_address,unit_owner_contact,driver_name,driver_address,driver_contact,engine_number,chassis_number,release_date,release_time,released_by,release_witness,violations(violation_code,violation_type,ticket_number,classification,discounted,franchise_number,apprehending_officers,treasurer_receipt_path,treasurer_receipt_number)";
  const violationFields="id,subject_name,violation_code,violation_type,ticket_number,penalty,classification,discounted,franchise_number,apprehending_officers,treasurer_receipt_path,treasurer_receipt_number,drivers(full_name,address,contact_number,franchises(operator_name,address,contact_number,engine_number,chassis_number))";
  const [paymentResult,violationResult]=await Promise.all([supabase.from("payments").select(paymentFields).order("paid_at",{ascending:false}),supabase.from("violations").select(violationFields).eq("status","pending").not("treasurer_receipt_path","is",null).order("occurred_at",{ascending:false})]);
  if(paymentResult.error)return alert(`Could not load payments: ${paymentResult.error.message}`); if(violationResult.error)return alert(`Could not load tickets ready for payment: ${violationResult.error.message}`);
  payments=(paymentResult.data||[]).map(normalize); pendingViolations=violationResult.data||[];
  document.getElementById("paymentViolation").innerHTML='<option value="">Select a ticket with submitted Treasurer receipt</option>'+pendingViolations.map((v)=>`<option value="${v.id}">${escapeHtml(v.ticket_number||"No ticket")} · ${escapeHtml(v.violation_code)} · ${escapeHtml(v.subject_name)} · ${peso(Math.max(Number(v.penalty||0)-Number(v.discounted||0),0))}</option>`).join(""); updateTotals(); applyFilters();
}

function officialHeader(code) { const tfro=new URL("../Logo/TFRO Logo.jpg",location.href).href, city=new URL("../Logo/Lucena City Logo.png",location.href).href; return `<header><div><h1>TRICYCLE FRANCHISING AND REGULATORY OFFICE</h1><p>City Government of Lucena | Republic of the Philippines</p><small>Hotline: 09395471681 | E-mail address: tfrolucena2025@gmail.com</small></div><img src="${tfro}"><img src="${city}"><b>TFRO - ${code}</b></header>`; }
function shell(title,code,body) { return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>*{box-sizing:border-box}body{margin:0;background:#d9dcda;font-family:Arial,sans-serif}.toolbar{position:sticky;top:0;z-index:5;padding:10px;text-align:center;background:#153e31;color:#fff}.toolbar button{margin-left:12px;padding:8px 15px;border:0;border-radius:7px;font-weight:800}.sheet{width:980px;min-height:680px;margin:18px auto;padding:24px 48px;background:#fff}header{height:108px;position:relative;display:flex;gap:10px;align-items:flex-start;padding:16px 18px;color:#fff;background:linear-gradient(130deg,#063b25 0 57%,#fff 57% 59%,#167349 59% 64%,#fff 64% 66%,#71a842 66% 71%,#fff 71% 73%,#e3df1c 73% 78%,#fff 78%)}header h1{margin:0;color:#fff600;font-size:20px}header p{margin:7px 0;font-size:13px}header small{position:absolute;left:0;bottom:0;width:56%;padding:5px 18px;background:#fff600;color:#15432f}header img{width:62px;height:62px;object-fit:contain;border-radius:50%}header b{position:absolute;right:12px;bottom:-28px;padding:7px 25px;background:#5687bf;color:#071b31;letter-spacing:2px}.title{text-align:center;margin:46px 0 22px;letter-spacing:5px;text-decoration:underline}.line{display:inline-block;min-width:180px;padding:2px 5px;border-bottom:1px solid #111}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px 25px}.grid p{margin:3px 0}table{width:100%;margin:20px 0;border-collapse:collapse}th,td{height:30px;padding:6px;border:1px solid #111;text-align:left}.three{display:grid;grid-template-columns:1fr 1fr 1fr;gap:25px;margin-top:35px}.sign{text-align:center}.sign .line{margin-top:25px}.note{margin:18px 0;padding:12px;border:1px solid #111}@page{size:landscape;margin:8mm}@media print{body{background:#fff}.toolbar{display:none}.sheet{width:100%;margin:0}}</style></head><body><div class="toolbar">Official connected record <button onclick="window.print()">Print / Save PDF</button></div><main class="sheet">${officialHeader(code)}${body}</main></body></html>`; }
function orderDocument(p) { const s=p.receipt_snapshot||{},v=p.violations||{},amount=s.amount_paid??p.amount; return shell(`TFRO-009 ${p.receipt}`,"009",`<h2 class="title">ORDER OF PAYMENT</h2><div class="grid"><p>Payor: <span class="line">${escapeHtml(s.payer||p.payer)}</span></p><p>Apprehending Officer/s: <span class="line">${escapeHtml(s.apprehending_officers||v.apprehending_officers||"")}</span></p><p>Address: <span class="line">${escapeHtml(s.address||p.unit_owner_address||"")}</span></p><p>Ticket No.: <span class="line">${escapeHtml(s.ticket_number||v.ticket_number||"")}</span></p></div><table><tr><th>Code</th><th>Violation</th><th>Penalty</th></tr><tr><td>${escapeHtml(s.code||v.violation_code||"")}</td><td>${escapeHtml(s.violation||v.violation_type||"")}</td><td>${peso(s.penalty??amount)}</td></tr><tr><td colspan="2">Discounted Amount</td><td>${peso(s.discounted||0)}</td></tr><tr><th colspan="2">Total Amount Due</th><th>${peso(amount)}</th></tr></table><div class="three"><div>OR. No. <span class="line">${escapeHtml(p.receipt)}</span><br>Amount Paid <span class="line">${peso(amount)}</span><br>Date Paid <span class="line">${escapeHtml(p.date)}</span></div><div class="sign"><b>Assessed by:</b><br><span class="line">${escapeHtml(s.assessed_by||"TFRO Personnel")}</span><br>TFRO Personnel</div><div class="sign"><b>Noted by:</b><br><span class="line">CRISELDA C. DAVID, DPA</span><br>TFRO Head</div></div>`); }
function releaseDocument(p) { const v=p.violations||{}; return shell(`TFRO-010 ${p.receipt}`,"010",`<h2 class="title">VEHICLE/UNIT RELEASING SLIP</h2><div class="grid"><p>Name of Unit Owner: <span class="line">${escapeHtml(p.unit_owner_name||p.payer)}</span></p><p>Date: <span class="line">${escapeHtml(p.release_date||p.date)}</span></p><p>Address: <span class="line">${escapeHtml(p.unit_owner_address||"")}</span></p><p>Contact Number: <span class="line">${escapeHtml(p.unit_owner_contact||"")}</span></p><p>Name of Driver: <span class="line">${escapeHtml(p.driver_name||p.payer)}</span></p><p>Driver Contact: <span class="line">${escapeHtml(p.driver_contact||"")}</span></p><p>Driver Address: <span class="line">${escapeHtml(p.driver_address||"")}</span></p><p>Apprehending Enforcer: <span class="line">${escapeHtml(v.apprehending_officers||"")}</span></p></div><div class="note"><b>Impoundment Information</b><div class="grid"><p>Engine No.: <span class="line">${escapeHtml(p.engine_number||"")}</span></p><p>Chassis No.: <span class="line">${escapeHtml(p.chassis_number||"")}</span></p></div></div><div class="grid"><p>OR. No.: <span class="line">${escapeHtml(p.receipt)}</span></p><p>Amount Paid: <span class="line">${peso(p.amount)}</span></p><p>Date Paid: <span class="line">${escapeHtml(p.date)}</span></p><p>Time Released: <span class="line">${escapeHtml(p.release_time||"")}</span></p></div><div class="three"><div class="sign"><b>Released by:</b><br><span class="line">${escapeHtml(p.released_by||"")}</span><br>Impounding Enforcer<br>Witness: ${escapeHtml(p.release_witness||"____________")}</div><div class="sign"><b>Recorded by:</b><br><span class="line">${escapeHtml(p.receipt_snapshot?.assessed_by||"TFRO Staff")}</span><br>TFRO STAFF</div><div class="sign"><b>Approved by:</b><br><span class="line">CRISELDA C. DAVID, DPA</span><br>TFRO Head/CDGH II</div></div>`); }
function openDocument(html) { const tab=open("","_blank"); if(!tab)return alert("Please allow pop-ups to view the document."); tab.document.open(); tab.document.write(html); tab.document.close(); }
async function openProof(p) { const path=p.violations?.treasurer_receipt_path; if(!path)return; const result=await supabase.storage.from("treasurer-receipts").createSignedUrl(path,600); if(result.error)return alert(result.error.message); open(result.data.signedUrl,"_blank","noopener"); }

function fillDetails(v) { const driver=v?.drivers||{},franchise=driver.franchises||{}; form.elements.payer.value=v?.subject_name||""; form.elements.amount.value=v?Math.max(Number(v.penalty||0)-Number(v.discounted||0),0).toFixed(2):""; form.elements.receipt.value=v?.treasurer_receipt_number||""; form.elements.unit_owner_name.value=franchise.operator_name||v?.subject_name||""; form.elements.unit_owner_address.value=franchise.address||""; form.elements.unit_owner_contact.value=franchise.contact_number||""; form.elements.driver_name.value=driver.full_name||v?.subject_name||""; form.elements.driver_address.value=driver.address||""; form.elements.driver_contact.value=driver.contact_number||""; form.elements.engine_number.value=franchise.engine_number||""; form.elements.chassis_number.value=franchise.chassis_number||""; form.elements.released_by.value=v?.apprehending_officers||""; }
function closeModal(){modal.hidden=true;form.reset();}
document.getElementById("recordPaymentBtn").addEventListener("click",()=>{modal.hidden=false;const today=new Date().toISOString().slice(0,10);form.elements.paid_date.value=today;form.elements.release_date.value=today;form.elements.release_time.value=new Date().toTimeString().slice(0,5);});
document.getElementById("closePaymentModal").addEventListener("click",closeModal); document.getElementById("cancelPaymentBtn").addEventListener("click",closeModal); document.getElementById("paymentViolation").addEventListener("change",(e)=>fillDetails(pendingViolations.find((row)=>String(row.id)===e.target.value))); document.getElementById("searchInput").addEventListener("input",applyFilters); document.getElementById("statusFilter").addEventListener("change",applyFilters);
form.addEventListener("submit",async(event)=>{event.preventDefault();const button=form.querySelector('[type="submit"]'),d=Object.fromEntries(new FormData(form));button.disabled=true;const record={receipt:d.receipt.trim(),payer:d.payer.trim(),payment_type:"penalty",amount:Number(d.amount),status:"paid",paid_at:`${d.paid_date}T00:00:00+08:00`,violation_id:Number(d.violation_id),recorded_by:currentUserId,unit_owner_name:d.unit_owner_name.trim(),unit_owner_address:d.unit_owner_address.trim()||null,unit_owner_contact:d.unit_owner_contact.trim()||null,driver_name:d.driver_name.trim(),driver_address:d.driver_address.trim()||null,driver_contact:d.driver_contact.trim()||null,engine_number:d.engine_number.trim()||null,chassis_number:d.chassis_number.trim()||null,release_date:d.release_date,release_time:d.release_time,released_by:d.released_by.trim()||null,release_witness:d.release_witness.trim()||null};const result=await supabase.from("payments").insert(record).select("id").single();button.disabled=false;if(result.error)return alert(`Could not secure payment: ${result.error.message}`);await logAudit({action:"Recorded Violation Payment and Release",actionType:"create",record:record.receipt,description:`Recorded payment and TFRO-010 details for ticket ${d.violation_id}.`});closeModal();await loadPayments();const saved=payments.find((p)=>p.id===result.data.id);if(saved)openDocument(orderDocument(saved));});
table.addEventListener("click",(event)=>{const button=event.target.closest("button[data-action]");if(!button)return;const p=payments.find((row)=>String(row.id)===button.dataset.id);if(!p)return;if(button.dataset.action==="order")openDocument(orderDocument(p));if(button.dataset.action==="release")openDocument(releaseDocument(p));if(button.dataset.action==="proof")void openProof(p);});
(async()=>{if(await verifyAccess())await loadPayments();})();
