import { supabase } from "./supabase.js";
import { requireRole } from "./auth-guard.js";
import { logAudit } from "./audit-helper.js";
import { openPaymentOrderPdfForm, openUnitReleasePdfForm } from "./pdf-form.js?v=20260828-3";

let payments = [], pendingViolations = [], currentUserId = null, currentRole = null, editingPaymentId = null;
const table = document.getElementById("paymentsTable"), modal = document.getElementById("paymentModal"), form = document.getElementById("paymentForm");
const peso = (amount) => "₱" + Number(amount || 0).toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#039;", '"':"&quot;" })[char]);
const normalize = (payment) => ({ ...payment, receipt:payment.receipt || `LEGACY-${payment.id}`, payer:payment.payer || "Unknown payer", type:payment.payment_type || "Penalty", status:payment.status || "paid", date:payment.paid_at ? String(payment.paid_at).slice(0,10) : "—" });

async function verifyAccess() {
  const { user, profile } = await requireRole(["staff", "admin"]);
  currentUserId = user?.id || null; currentRole = profile?.role || null;
  document.getElementById("recordPaymentBtn").hidden = currentRole !== "staff";
  document.querySelector(".topbar h1").textContent = currentRole === "admin" ? "Administrator — Payment & Release Records" : "TFRO Staff / PAYA — Violation Payments";
  return Boolean(user);
}

function render(rows) {
  table.innerHTML = rows.length ? rows.map((payment) => { const violation = payment.violations || {}; return `<tr><td>${escapeHtml(payment.receipt)}</td><td>${escapeHtml(payment.payer)}</td><td><span class="type penalty">${escapeHtml(payment.type)}</span></td><td>${escapeHtml(violation.classification || "—")}</td><td>${peso(violation.discounted)}</td><td>${peso(payment.amount)}</td><td>${escapeHtml(payment.date)}</td><td><span class="status ${escapeHtml(payment.status)}">${escapeHtml(payment.status)}</span></td><td><div class="actions"><button type="button" data-action="order" data-id="${payment.id}" title="View/download TFRO-009"><i class="ri-file-pdf-2-line"></i> 009</button><button type="button" data-action="release" data-id="${payment.id}" title="View/download TFRO-010"><i class="ri-file-pdf-2-line"></i> 010</button><button type="button" data-action="edit" data-id="${payment.id}" title="Edit payment/release details"><i class="ri-pencil-line"></i></button>${violation.treasurer_receipt_path ? `<button type="button" data-action="proof" data-id="${payment.id}" title="View City Treasurer receipt"><i class="ri-image-line"></i></button>` : ""}</div></td></tr>`; }).join("") : '<tr><td colspan="9">No payments recorded.</td></tr>';
}
function applyFilters() { const term=document.getElementById("searchInput").value.trim().toLowerCase(), status=document.getElementById("statusFilter").value; render(payments.filter((payment)=>(status==="all"||payment.status===status)&&`${payment.payer} ${payment.receipt} ${payment.violations?.ticket_number||""}`.toLowerCase().includes(term))); }
function updateTotals() { const collected=payments.filter((p)=>p.status==="paid").reduce((sum,p)=>sum+Number(p.amount),0); document.getElementById("totalCollected").textContent=peso(collected); document.getElementById("apprehenderShare").textContent=peso(collected*.2); document.getElementById("pendingCount").textContent=pendingViolations.length; document.getElementById("overdueCount").textContent=payments.filter((p)=>p.status==="overdue").length; }

async function loadPayments() {
  const paymentFields="id,receipt,payer,payment_type,amount,status,paid_at,violation_id,receipt_snapshot,unit_owner_name,unit_owner_address,unit_owner_contact,driver_name,driver_address,driver_contact,engine_number,chassis_number,release_date,release_time,released_by,release_witness,violations(violation_code,violation_type,ticket_number,classification,discounted,franchise_number,apprehending_officers,treasurer_receipt_path,treasurer_receipt_number)";
  const violationFields="id,subject_name,violation_code,violation_type,ticket_number,penalty,classification,discounted,franchise_number,apprehending_officers,treasurer_receipt_path,treasurer_receipt_number,drivers(full_name,address,contact_number,franchises(operator_name,address,contact_number,engine_number,chassis_number))";
  const [paymentResult,violationResult]=await Promise.all([supabase.from("payments").select(paymentFields).order("paid_at",{ascending:false}),supabase.from("violations").select(violationFields).eq("status","pending").not("treasurer_receipt_path","is",null).order("occurred_at",{ascending:false})]);
  if(paymentResult.error)return alert(`Could not load payments: ${paymentResult.error.message}`); if(violationResult.error)return alert(`Could not load tickets ready for payment: ${violationResult.error.message}`);
  payments=(paymentResult.data||[]).map(normalize); pendingViolations=violationResult.data||[];
  document.getElementById("paymentViolation").innerHTML='<option value="">Select a ticket with submitted Treasurer receipt</option>'+pendingViolations.map((v)=>`<option value="${v.id}">${escapeHtml(v.ticket_number||"No ticket")} · ${escapeHtml(v.violation_code)} · ${escapeHtml(v.subject_name)} · ${peso(Math.max(Number(v.penalty||0)-Number(v.discounted||0),0))}</option>`).join(""); updateTotals(); applyFilters();
}

async function openProof(p) { const path=p.violations?.treasurer_receipt_path; if(!path)return; const result=await supabase.storage.from("treasurer-receipts").createSignedUrl(path,600); if(result.error)return alert(result.error.message); open(result.data.signedUrl,"_blank","noopener"); }

function fillDetails(v) { const driver=v?.drivers||{},franchise=driver.franchises||{}; form.elements.payer.value=v?.subject_name||""; form.elements.amount.value=v?Math.max(Number(v.penalty||0)-Number(v.discounted||0),0).toFixed(2):""; form.elements.receipt.value=v?.treasurer_receipt_number||""; form.elements.unit_owner_name.value=franchise.operator_name||v?.subject_name||""; form.elements.unit_owner_address.value=franchise.address||""; form.elements.unit_owner_contact.value=franchise.contact_number||""; form.elements.driver_name.value=driver.full_name||v?.subject_name||""; form.elements.driver_address.value=driver.address||""; form.elements.driver_contact.value=driver.contact_number||""; form.elements.engine_number.value=franchise.engine_number||""; form.elements.chassis_number.value=franchise.chassis_number||""; form.elements.released_by.value=v?.apprehending_officers||""; }
function setCoreFieldsDisabled(disabled) { ["paymentViolation","paymentPayer"].forEach((id)=>{document.getElementById(id).disabled=disabled;}); ["receipt","paid_date","amount"].forEach((name)=>{form.elements[name].disabled=disabled;}); }
function closeModal(){modal.hidden=true;editingPaymentId=null;setCoreFieldsDisabled(false);form.reset();document.getElementById("paymentModalTitle").textContent="Record Payment";form.querySelector('[type="submit"]').innerHTML='<i class="ri-lock-line"></i> Secure Payment';}
function openNewPayment(){editingPaymentId=null;setCoreFieldsDisabled(false);modal.hidden=false;const today=new Date().toISOString().slice(0,10);form.elements.paid_date.value=today;form.elements.release_date.value=today;form.elements.release_time.value=new Date().toTimeString().slice(0,5);}
function openEditPayment(payment){editingPaymentId=payment.id;modal.hidden=false;document.getElementById("paymentModalTitle").textContent="Edit Payment / Releasing Slip Details";form.elements.violation_id.value=payment.violation_id||"";form.elements.payer.value=payment.payer||"";form.elements.receipt.value=payment.receipt||"";form.elements.paid_date.value=payment.date||"";form.elements.amount.value=payment.amount||0;["unit_owner_name","unit_owner_address","unit_owner_contact","driver_name","driver_address","driver_contact","engine_number","chassis_number","release_date","release_time","released_by","release_witness"].forEach((name)=>{form.elements[name].value=payment[name]||"";});setCoreFieldsDisabled(true);form.querySelector('[type="submit"]').innerHTML='<i class="ri-save-line"></i> Save Updated Details';}
document.getElementById("recordPaymentBtn").addEventListener("click",openNewPayment);
document.getElementById("closePaymentModal").addEventListener("click",closeModal); document.getElementById("cancelPaymentBtn").addEventListener("click",closeModal); document.getElementById("paymentViolation").addEventListener("change",(e)=>fillDetails(pendingViolations.find((row)=>String(row.id)===e.target.value))); document.getElementById("searchInput").addEventListener("input",applyFilters); document.getElementById("statusFilter").addEventListener("change",applyFilters);
form.addEventListener("submit",async(event)=>{event.preventDefault();const button=form.querySelector('[type="submit"]'),d=Object.fromEntries(new FormData(form));button.disabled=true;const releaseDetails={unit_owner_name:d.unit_owner_name.trim(),unit_owner_address:d.unit_owner_address.trim()||null,unit_owner_contact:d.unit_owner_contact.trim()||null,driver_name:d.driver_name.trim(),driver_address:d.driver_address.trim()||null,driver_contact:d.driver_contact.trim()||null,engine_number:d.engine_number.trim()||null,chassis_number:d.chassis_number.trim()||null,release_date:d.release_date,release_time:d.release_time,released_by:d.released_by.trim()||null,release_witness:d.release_witness.trim()||null};let result;if(editingPaymentId){result=await supabase.from("payments").update(releaseDetails).eq("id",editingPaymentId).select("id").single();}else{const record={...releaseDetails,receipt:d.receipt.trim(),payer:d.payer.trim(),payment_type:"penalty",amount:Number(d.amount),status:"paid",paid_at:`${d.paid_date}T00:00:00+08:00`,violation_id:Number(d.violation_id),recorded_by:currentUserId};result=await supabase.from("payments").insert(record).select("id").single();}button.disabled=false;if(result.error)return alert(`Could not save payment details: ${result.error.message}`);await logAudit({action:editingPaymentId?"Updated Payment Release Details":"Recorded Violation Payment and Release",actionType:editingPaymentId?"update":"create",record:String(result.data.id),description:editingPaymentId?"Updated TFRO-010 owner, driver, vehicle, and release details.":`Recorded payment and TFRO-010 details for ticket ${d.violation_id}.`});const wasEditing=Boolean(editingPaymentId);closeModal();await loadPayments();if(!wasEditing){const saved=payments.find((p)=>p.id===result.data.id);if(saved)void openPaymentOrderPdfForm({payment:saved,violation:saved.violations||{},editable:currentRole==="admin"});}});
table.addEventListener("click",(event)=>{const button=event.target.closest("button[data-action]");if(!button)return;const p=payments.find((row)=>String(row.id)===button.dataset.id);if(!p)return;const editable=currentRole==="admin";if(button.dataset.action==="order")void openPaymentOrderPdfForm({payment:p,violation:p.violations||{},editable});if(button.dataset.action==="release")void openUnitReleasePdfForm({payment:p,violation:p.violations||{},editable});if(button.dataset.action==="edit")openEditPayment(p);if(button.dataset.action==="proof")void openProof(p);});
(async()=>{if(await verifyAccess())await loadPayments();})();
