import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const FORMS = [
  ['001', 'Temporary MTOP'], ['002', 'Petition for Dropping'], ['003', 'PMBL Certification'],
  ['004', 'Renewal Checklist'], ['005', 'MTOP Application'], ['007', 'Certification of Dropping'],
  ['009', 'Order of Payment'], ['010', 'Unit Releasing Slip'],
];

function Fill({ name, data, setData, className = '' }) {
  return <input className={`fill ${className}`} aria-label={name} value={data[name] || ''} onChange={e => setData({ ...data, [name]: e.target.value })} />;
}
function Header({ code, pmbl = false, landscape = false }) {
  const src = pmbl ? '/assets/pmbl-header.png' : landscape ? '/assets/tfro-header-landscape.png' : '/assets/tfro-header.png';
  return <header className={`paper-header ${pmbl ? 'pmbl' : ''}`}><img src={src} /><span>TFRO - {code}</span></header>;
}
const Line = ({ children }) => <div className="line">{children}</div>;
function Vehicle({ data, setData }) {
  return <table className="vehicle"><thead><tr>{['MAKE','MODEL','MOTOR NO.','CHASSIS NO.','PLATE NO.'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody><tr>{['make','model','motor','chassis','plate'].map(x=><td key={x}><Fill name={x} data={data} setData={setData}/></td>)}</tr></tbody></table>;
}
function MTOP({ data, setData }) {
  return <Paper><Header code="001"/><h1>MOTORIZED TRICYCLE OPERATOR’S PERMIT</h1><div className="two-col"><Line>Name: <Fill name="name" data={data} setData={setData}/></Line><Line>Franchise No. <Fill name="franchise" data={data} setData={setData}/></Line></div><Line>Address: <Fill name="address" data={data} setData={setData}/></Line><p>Applicant is hereby authorized to operate a motorized tricycle service for hire on the route</p><h3>LUCENA CITY PROPER</h3><p>Using one (1) tricycle unit described as follows:</p><Vehicle data={data} setData={setData}/><p className="justify">Applicant / Operator shall comply with all rules and regulations prescribed by the TFRC. Failure to comply with any conditions herein shall be sufficient cause for suspension or cancellation of the authority granted.</p><ol className="terms"><li>The unit shall be registered as FOR HIRE with the Land Transportation Office in Lucena City.</li><li>Within the authorized route, applicant shall charge the fare rate provided by existing City Ordinance.</li><li>This permit shall constitute the franchise authority to operate the unit described herein for hire.</li><li>Without TFRC authority, the operator shall not transfer, increase, drop, or substitute a unit or abandon the authorized service.</li><li>Required Mayor’s Permit and Supervision Fees shall be paid when due.</li><li>Applicant shall not operate outside the authorized route except where permitted by law.</li><li>Any unauthorized addition, alteration, or deletion invalidates this document.</li></ol><div className="ordered"><b>SO ORDERED</b><div className="grant">GRANTED<br/>GOOD UNTIL <Fill name="valid_until" data={data} setData={setData}/></div></div><p className="notice">NOTE: This Temporary Motorized Tricycle Operator’s Permit is valid for 15 days only, intended for reclassification purposes.</p><Signature name="CRISELDA C. DAVID, DPA" role="TFRO HEAD"/></Paper>;
}
function Petition({ data, setData }) { return <Paper><Header code="002"/><div className="agency">Republic of the Philippines<br/>Office of the Sangguniang Panglungsod<br/><b>TRICYCLE FRANCHISING &amp; REGULATORY OFFICE</b><br/>Lucena City</div><div className="two-col"><Line>Petitioner <Fill name="petitioner" data={data} setData={setData}/></Line><Line>CASE No. <Fill name="case" data={data} setData={setData}/></Line><Line>TODA: <Fill name="toda" data={data} setData={setData}/></Line><Line>Contact No. <Fill name="contact" data={data} setData={setData}/></Line></div><h1 className="spaced">P E T I T I O N</h1><p><b>PETITIONER</b>, to this honourable Committee most respectfully states;</p><Line>That the petitioner is of legal age, single/married, Filipino citizen and residing at <Fill name="address" data={data} setData={setData}/></Line><p>That petitioner is the owner/vendee of one (1) unit of tricycle described as follows:</p><Vehicle data={data} setData={setData}/><Line>Covered by MTOP/Franchise on the route <Fill name="route" data={data} setData={setData}/></Line><Line>In the name of <Fill name="registered" data={data} setData={setData}/> to be dropped/cancelled because <Fill name="reason" data={data} setData={setData}/></Line><Line>Supporting papers: <Fill name="papers" data={data} setData={setData}/></Line><p>WHEREFORE, it is respectfully prayed that after due consideration the foregoing petition be granted.</p><Signature name="" role="Petitioner"/><h2 className="spaced">V E R I F I C A T I O N</h2><p className="justify">I, <Fill name="affiant" data={data} setData={setData}/>, after being sworn to law, depose and say that I caused the preparation of this petition, have read and understood it, and that its allegations and attachments are true and correct.</p><Signature name="" role="Affiant"/><p>SUBSCRIBED AND SWORN before me this <Fill name="sworn_date" data={data} setData={setData}/>.</p></Paper> }
function PMBL({data,setData}) { return <Paper landscape><Header code="003" pmbl/><h1>CERTIFICATION</h1><h2 className="left">TO WHOM IT MAY CONCERN:</h2><p className="letter">This is to certify that Mr./Ms. <Fill name="name" data={data} setData={setData}/>, with TFRO Franchise No. <Fill name="franchise" data={data} setData={setData}/>, of legal age, a resident of <Fill name="address" data={data} setData={setData}/>, is a bonafide member of the <Fill name="toda" data={data} setData={setData}/> TODA, serving as a <label>□ Driver</label> / <label>□ Operator</label> / <label>□ both</label>.</p><p className="letter">Based on the records of this Association, he/she has no pending obligations, complaints, or violations and is in good standing as of this date.</p><p className="letter">This certification is issued upon the request of the above-named person for whatever legal purpose it may serve.</p><Line>Issued this <Fill name="day" data={data} setData={setData}/> day of <Fill name="month" data={data} setData={setData}/>, 20<Fill name="year" data={data} setData={setData}/> at Lucena City, Philippines.</Line><div className="sign-grid"><Signature name="" role="TODA President/Authorized officer"/><Signature name="ERLITO D. SALES" role="PMBL President"/></div></Paper> }
function Checklist({data,setData}) { const req=['Receipts of payments from the City Treasurer’s Office','Certificate of payment from LTO for updated registration','Latest Voter’s Certificate of Registration','Valid common carrier’s insurance','Latest Community Tax Certificate','Barangay Clearance','Driver’s License','Two 2×2 photos','Certification of Membership from an accredited TODA']; const phys=['Functional horn that does not emit exceptionally loud or startling sound.','Functional signal lights, front and back.','Functional tail light, including license plate light.','Functional white headlight and red tail light.','Functional light installed inside the sidecar.','Functional anti-noise equipment and mufflers.','Body number sticker prominently displayed.','Garbage receptacle.','Clean windshield.']; return <Paper landscape><Header code="004" landscape/><Line>Date: <Fill name="date" data={data} setData={setData}/></Line><h1>CHECKLIST OF REQUIREMENTS</h1><h3>REQUIREMENTS FOR THE RENEWAL OF MTOP</h3><div className="check-list">{req.map((r,i)=><label key={r}><input type="checkbox"/> {String.fromCharCode(97+i)}) {r}</label>)}</div><p className="note">Note: A grace period of 60 days shall be given to an unrenewed MTOP. Applicable surcharge will be imposed after the grace period.</p><h3>PHYSICAL REQUIREMENTS</h3><table className="check-table"><thead><tr><th>PASS</th><th>FAIL</th><th>REQUIREMENTS</th></tr></thead><tbody>{phys.map(r=><tr key={r}><td><input type="checkbox"/></td><td><input type="checkbox"/></td><td>{r}</td></tr>)}</tbody></table><div className="sign-grid three"><Signature name="KATURUNGAN A. AFABLE" role="TFRO Staff"/><Signature name="MARCEL A. MENDOZA" role="In-Charge, Admin Unit"/><Signature name="CRISELDA C. DAVID, DPA" role="TFRO Head"/></div></Paper> }
function Application({data,setData}) { return <Paper><Header code="005"/><h1 className="dark">Application for MOTORIZED TRICYCLE OPERATOR PERMIT</h1><div className="form-grid"><Line>DATE: <Fill name="date" data={data} setData={setData}/></Line><Line>☐ NEW &nbsp; ☐ RENEWAL</Line><Line>FRANCHISE NO. <Fill name="franchise" data={data} setData={setData}/></Line><Line>CONTACT NUMBER <Fill name="contact" data={data} setData={setData}/></Line></div><h3 className="section">NAME OF APPLICANT</h3><div className="three-col">{['Last Name','First Name','Middle Name'].map(x=><Line key={x}>{x}<Fill name={x} data={data} setData={setData}/></Line>)}</div><h3 className="section">RESIDENTIAL ADDRESS</h3><Line><Fill name="address" data={data} setData={setData}/></Line><div className="form-grid"><Line>BIRTHDATE <Fill name="birthdate" data={data} setData={setData}/></Line><Line>PLACE OF BIRTH <Fill name="birthplace" data={data} setData={setData}/></Line><Line>AGE <Fill name="age" data={data} setData={setData}/></Line><Line>CIVIL STATUS <Fill name="status" data={data} setData={setData}/></Line></div><h3 className="dark">DESCRIPTION OF VEHICLE</h3><Vehicle data={data} setData={setData}/><h3 className="dark">THIS APPLICATION PROPOSES TO OPERATE TRICYCLE SERVICE ROUTE ON — LUCENA PROPER</h3><p className="declaration">I hereby certify the correctness of the foregoing information. I am fully aware that any franchise permit issued is subject to all requirements of existing ordinances and rules promulgated by competent authorities of the City of Lucena.</p><Signature name="" role="Signature or RIGHT THUMBMARK of Applicant"/><h3>REQUIREMENTS:</h3><ol>{['Voter’s Certificate/Voter’s ID/Any government-issued ID','Barangay Clearance','Community Tax Certificate (Cedula)','Latest Registration OR/CR copy for verification','Tricycle unit for inspection','Police Clearance (For New Applicant)'].map(x=><li key={x}>{x}</li>)}</ol><div className="photo">2×2 PICTURE</div><hr className="dash"/><h2>DO NOT WRITE ANYTHING (FOR TFRC USE ONLY)</h2><div className="inspection">TAIL LIGHT ______ MC &nbsp; ______ Side Car<br/>SIGNAL LIGHT ______ Front &nbsp; ______ Rear<br/>HEADLIGHT ______ MC &nbsp; ______ Side Car<br/>BRAKES ______ Front &nbsp; ______ Rear<br/>HORN ______ Loud &nbsp; ______ Soft<br/>BODY COLOR __________________</div><div className="sign-grid"><Signature name="CRISELDA C. DAVID" role="TFRO HEAD"/><Signature name="MARK B. ALCALA" role="City Mayor"/></div></Paper> }
function Dropping({data,setData}) { return <Paper><Header code="007"/><h1 className="wide-title">C E R T I F I C A T I O N</h1><h2 className="subtle">of Dropping</h2><div className="drop-fields">{[['Owner','owner'],['Make','make'],['Motor No.','motor'],['Chassis No.','chassis'],['Plate No.','plate']].map(([a,b])=><Line key={b}>{a}: <Fill name={b} data={data} setData={setData}/></Line>)}</div><Signature name="CRISELDA C. DAVID, DPA" role="TFRO HEAD"/></Paper> }
function Payment({data,setData}) { const copy=(n)=><section className="payment-copy"><h1 className="spaced">ORDER OF PAYMENT</h1><div className="two-col"><Line>Payor: <Fill name={`payor${n}`} data={data} setData={setData}/></Line><Line>Apprehending Officer/s: <Fill name={`officer${n}`} data={data} setData={setData}/></Line></div><Line>Address: <Fill name={`address${n}`} data={data} setData={setData}/></Line><table className="check-table payment"><thead><tr><th>Code</th><th>Violation</th><th>Penalty</th></tr></thead><tbody>{Array.from({length:7},(_,i)=><tr key={i}><td><Fill name={`code${n}${i}`} data={data} setData={setData}/></td><td><Fill name={`violation${n}${i}`} data={data} setData={setData}/></td><td><Fill name={`penalty${n}${i}`} data={data} setData={setData}/></td></tr>)}<tr><th>Total Amount Due</th><td/><td><Fill name={`total${n}`} data={data} setData={setData}/></td></tr></tbody></table></section>; return <Paper><Header code="009"/>{copy(1)}<div className="payment-sign"><Signature name="" role="TFRO Personnel / Assessed by"/><Signature name="CRISELDA C. DAVID, DPA" role="TFRO Head / Noted by"/></div><Header code="009"/>{copy(2)}</Paper> }
function Release({data,setData}) { const slip=n=><section className="release"><h1>VEHICLE/UNIT RELEASING SLIP</h1><div className="two-col"><Line>Name of Unit Owner: <Fill name={`owner${n}`} data={data} setData={setData}/></Line><Line>Date: <Fill name={`date${n}`} data={data} setData={setData}/></Line></div><Line>Address: <Fill name={`address${n}`} data={data} setData={setData}/> Contact Number: <Fill name={`contact${n}`} data={data} setData={setData}/></Line><Line>Name of Driver: <Fill name={`driver${n}`} data={data} setData={setData}/></Line><h2>Impoundment information:</h2><Line>Engine No.: <Fill name={`engine${n}`} data={data} setData={setData}/></Line><Line>Chassis No.: <Fill name={`chassis${n}`} data={data} setData={setData}/></Line><Line>OR. No. <Fill name={`or${n}`} data={data} setData={setData}/></Line><Line>Amount Paid <Fill name={`amount${n}`} data={data} setData={setData}/></Line><Line>Date Paid <Fill name={`paid${n}`} data={data} setData={setData}/></Line><div className="release-grid"><Signature name="" role="TFRO STAFF / Recorded by"/><div className="impound"><b>Note: To be filled up by Impounding Personnel only</b><Signature name="" role="Impounding Enforcer / Released by"/><p>Witness: __________________</p><p>Time: ______ Date: ________</p><b>JONATHAN R. CARURUCAN</b><br/>In-Charge, Impounding Section</div></div><Signature name="CRISELDA C. DAVID, DPA" role="TFRO Head/CDGH II"/></section>; return <Paper><Header code="010"/>{slip(1)}<Header code="010"/>{slip(2)}</Paper> }
function Signature({name,role}) { return <div className="signature"><div className="signature-line">{name}</div><span>{role}</span></div> }
function Paper({children,landscape=false}) { return <article className={`paper ${landscape?'landscape':''}`}>{children}<footer>TRICYCLE FRANCHISING AND REGULATORY OFFICE | OLD LUCENA CITY HALL BUILDING, M. L. TAGARAO STREET, BRGY. 5, LUCENA CITY, PHILIPPINES</footer></article> }
const components={'001':MTOP,'002':Petition,'003':PMBL,'004':Checklist,'005':Application,'007':Dropping,'009':Payment,'010':Release};
function App(){const [active,setActive]=useState('005'); const [data,setData]=useState(()=>JSON.parse(localStorage.getItem('tfro-forms')||'{}')); useEffect(()=>localStorage.setItem('tfro-forms',JSON.stringify(data)),[data]); const Form=components[active]; return <><aside><div className="brand"><b>TFRO</b><span>Digital Forms</span></div><nav>{FORMS.map(([id,name])=><button className={active===id?'active':''} onClick={()=>setActive(id)} key={id}><i>{id}</i><span>{name}</span></button>)}</nav><div className="saved">● Changes save automatically</div></aside><main><div className="toolbar"><div><small>FORM TFRO-{active}</small><h2>{FORMS.find(x=>x[0]===active)[1]}</h2></div><button onClick={()=>window.print()}>Print form</button></div><div className="canvas"><Form data={data[active]||{}} setData={v=>setData({...data,[active]:v})}/></div></main></>};
createRoot(document.getElementById('root')).render(<App/>);
