-- Traffic Enforcer accounts, verified signup, ticket-photo evidence, and
-- least-privilege access to Driver/violation records.

begin;

create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles
  add constraint profiles_role_check
  check (role in ('admin', 'staff', 'operator', 'traffic_enforcer'));

create table if not exists public.traffic_enforcers (
  id bigint generated by default as identity primary key,
  enforcer_id text not null unique,
  full_name text not null,
  email text,
  contact_number text,
  unit_assignment text,
  status text not null default 'active' check (status in ('active', 'suspended', 'inactive')),
  user_id uuid unique references auth.users(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint traffic_enforcers_id_format check (enforcer_id ~ '^[A-Z0-9][A-Z0-9-]{2,39}$')
);

alter table public.traffic_enforcers enable row level security;
revoke all on table public.traffic_enforcers from anon, authenticated;
grant select, insert, update on table public.traffic_enforcers to authenticated;
grant usage, select on sequence public.traffic_enforcers_id_seq to authenticated;

drop policy if exists "Administrators manage Traffic Enforcers" on public.traffic_enforcers;
create policy "Administrators manage Traffic Enforcers"
on public.traffic_enforcers for all to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));

drop policy if exists "Traffic Enforcers read their own record" on public.traffic_enforcers;
create policy "Traffic Enforcers read their own record"
on public.traffic_enforcers for select to authenticated
using (user_id = (select auth.uid()));

-- The Auth trigger validates the requested ID against the administrator's
-- active, unclaimed roster. raw_user_meta_data selects a flow but never grants
-- authority unless this server-side registry check succeeds.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested_role text := coalesce(new.raw_user_meta_data ->> 'role', 'operator');
  supplied_name text := nullif(btrim(new.raw_user_meta_data ->> 'full_name'), '');
  supplied_contact text := nullif(btrim(new.raw_user_meta_data ->> 'contact_number'), '');
  supplied_address text := nullif(btrim(new.raw_user_meta_data ->> 'address'), '');
  supplied_franchise text := nullif(upper(btrim(new.raw_user_meta_data ->> 'franchise_number')), '');
  supplied_enforcer_id text := nullif(upper(btrim(new.raw_user_meta_data ->> 'enforcer_id')), '');
  roster public.traffic_enforcers%rowtype;
begin
  if requested_role = 'traffic_enforcer' then
    if supplied_enforcer_id is null then
      raise exception 'A valid Traffic Enforcer ID is required.' using errcode = 'P0001';
    end if;

    select * into roster
    from public.traffic_enforcers
    where enforcer_id = supplied_enforcer_id
    for update;

    if not found or roster.status <> 'active' then
      raise exception 'Traffic Enforcer ID is not registered or active.' using errcode = 'P0001';
    end if;
    if roster.user_id is not null and roster.user_id <> new.id then
      raise exception 'Traffic Enforcer ID is already linked to an account.' using errcode = 'P0001';
    end if;

    insert into public.profiles (id, role, full_name, contact_number)
    values (new.id, 'traffic_enforcer', coalesce(roster.full_name, supplied_name), supplied_contact)
    on conflict (id) do update set
      role = 'traffic_enforcer',
      full_name = excluded.full_name,
      contact_number = coalesce(excluded.contact_number, public.profiles.contact_number);

    update public.traffic_enforcers
    set user_id = new.id,
        email = lower(new.email),
        contact_number = coalesce(supplied_contact, contact_number),
        updated_at = now()
    where id = roster.id;
  else
    -- Public non-enforcer signup remains Operator-only.
    insert into public.profiles (id, role, full_name, contact_number)
    values (new.id, 'operator', supplied_name, supplied_contact)
    on conflict (id) do update set
      full_name = coalesce(excluded.full_name, public.profiles.full_name),
      contact_number = coalesce(excluded.contact_number, public.profiles.contact_number);

    if supplied_name is not null and supplied_contact is not null
       and supplied_address is not null and supplied_franchise is not null then
      update public.operators
      set full_name = supplied_name, email = lower(new.email), address = supplied_address,
          contact_number = supplied_contact, franchise_number = supplied_franchise
      where user_id = new.id;
      if not found then
        insert into public.operators (
          user_id, full_name, email, address, contact_number,
          franchise_number, status, verified
        ) values (
          new.id, supplied_name, lower(new.email), supplied_address, supplied_contact,
          supplied_franchise, 'active', false
        );
      end if;
    end if;
  end if;
  return new;
end;
$$;

revoke all on function public.handle_new_user() from public, anon, authenticated;

alter table public.violations
  add column if not exists ticket_photo_path text,
  add column if not exists driver_id bigint references public.drivers(id) on delete set null;

grant select on table public.drivers, public.violations, public.violation_catalog to authenticated;
grant insert on table public.violations to authenticated;

drop policy if exists "Traffic Enforcers search Drivers" on public.drivers;
create policy "Traffic Enforcers search Drivers"
on public.drivers for select to authenticated
using (exists (
  select 1 from public.traffic_enforcers e
  where e.user_id = (select auth.uid()) and e.status = 'active'
));

drop policy if exists "Traffic Enforcers read their tickets" on public.violations;
create policy "Traffic Enforcers read their tickets"
on public.violations for select to authenticated
using (
  (driver_id is not null or recorded_by = (select auth.uid()))
  and exists (
    select 1 from public.traffic_enforcers e
    where e.user_id = (select auth.uid()) and e.status = 'active'
  )
);

drop policy if exists "Traffic Enforcers submit tickets" on public.violations;
create policy "Traffic Enforcers submit tickets"
on public.violations for insert to authenticated
with check (
  recorded_by = (select auth.uid())
  and status = 'pending'
  and exists (
    select 1 from public.traffic_enforcers e
    where e.user_id = (select auth.uid()) and e.status = 'active'
  )
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('violation-tickets', 'violation-tickets', false, 10485760, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Traffic Enforcers upload ticket photos" on storage.objects;
create policy "Traffic Enforcers upload ticket photos"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'violation-tickets'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
  and exists (
    select 1 from public.traffic_enforcers e
    where e.user_id = (select auth.uid()) and e.status = 'active'
  )
);

drop policy if exists "Authorized users read ticket photos" on storage.objects;
create policy "Authorized users read ticket photos"
on storage.objects for select to authenticated
using (
  bucket_id = 'violation-tickets'
  and (
    owner_id = (select auth.uid()::text)
    or exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role in ('admin','staff'))
  )
);

drop policy if exists "Traffic Enforcers remove own ticket photos" on storage.objects;
create policy "Traffic Enforcers remove own ticket photos"
on storage.objects for delete to authenticated
using (bucket_id = 'violation-tickets' and owner_id = (select auth.uid()::text));

create or replace function private.notify_enforcer_ticket_submission()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if exists (
    select 1 from public.profiles p
    where p.id = new.recorded_by and p.role = 'traffic_enforcer'
  ) then
    insert into public.notifications (title, message, type, user_id)
    select
      'Traffic Enforcer Ticket Submitted',
      'Ticket ' || coalesce(new.ticket_number, new.id::text) || ' for ' || new.subject_name ||
        ' was submitted with photo evidence for TFRO review.',
      'warning',
      p.id
    from public.profiles p
    where p.role in ('admin', 'staff');
  end if;
  return new;
end;
$$;

revoke all on function private.notify_enforcer_ticket_submission() from public, anon, authenticated;
drop trigger if exists notify_enforcer_ticket_submission on public.violations;
create trigger notify_enforcer_ticket_submission
after insert on public.violations
for each row execute function private.notify_enforcer_ticket_submission();

-- Admins already read audit logs through the existing staff/admin policy.
-- Enforcers may only read their own activity for their portal history.
drop policy if exists "Traffic Enforcers read their own audit log" on public.audit_logs;
create policy "Traffic Enforcers read their own audit log"
on public.audit_logs for select to authenticated
using (
  user_id = (select auth.uid())
  and exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'traffic_enforcer')
);

create index if not exists drivers_license_number_lower_idx on public.drivers (lower(license_number));
create index if not exists violations_recorded_by_idx on public.violations (recorded_by);
create index if not exists traffic_enforcers_user_id_idx on public.traffic_enforcers (user_id);

notify pgrst, 'reload schema';
commit;
