begin;

create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

create or replace function private.is_current_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.profiles profile
      where profile.id = (select auth.uid())
        and profile.role = 'admin'
    );
$$;

revoke all on function private.is_current_admin() from public, anon;
grant execute on function private.is_current_admin() to authenticated;

-- Franchise administration is an Admin page. Staff retains read access for
-- violation/payment processing but can no longer create or alter master rows.
drop policy if exists "Staff can add franchises" on public.franchises;
create policy "Administrators add franchises"
on public.franchises for insert to authenticated
with check ((select private.is_current_admin()));

drop policy if exists "Staff can update franchises" on public.franchises;
create policy "Administrators update franchises"
on public.franchises for update to authenticated
using ((select private.is_current_admin()))
with check ((select private.is_current_admin()));

create table if not exists public.operator_receipt_submissions (
  id bigint generated by default as identity primary key,
  violation_id bigint not null references public.violations(id) on delete cascade,
  operator_id uuid not null references auth.users(id) on delete cascade,
  receipt_number text,
  storage_path text not null,
  submitted_at timestamptz not null default now(),
  unique (violation_id)
);

alter table public.operator_receipt_submissions enable row level security;
revoke all on table public.operator_receipt_submissions from anon, authenticated;
grant select, insert on table public.operator_receipt_submissions to authenticated;
grant usage, select on sequence public.operator_receipt_submissions_id_seq to authenticated;

drop policy if exists "Operators submit linked Treasurer receipts" on public.operator_receipt_submissions;
create policy "Operators submit linked Treasurer receipts"
on public.operator_receipt_submissions for insert to authenticated
with check (
  operator_id = (select auth.uid())
  and split_part(storage_path, '/', 1) = (select auth.uid())::text
  and exists (
    select 1 from public.profiles profile
    where profile.id = (select auth.uid()) and profile.role = 'operator'
  )
);

drop policy if exists "Authorized users read receipt submissions" on public.operator_receipt_submissions;
create policy "Authorized users read receipt submissions"
on public.operator_receipt_submissions for select to authenticated
using (
  operator_id = (select auth.uid())
  or (select private.is_tfro_staff())
);

create or replace function private.process_operator_receipt_submission()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.operator_id is distinct from (select auth.uid()) then
    raise exception 'Receipt submission identity does not match the signed-in account.' using errcode = '42501';
  end if;

  update public.violations violation
     set treasurer_receipt_path = new.storage_path,
         treasurer_receipt_number = nullif(btrim(new.receipt_number), ''),
         treasurer_receipt_submitted_at = new.submitted_at,
         treasurer_receipt_submitted_by = new.operator_id
   where violation.id = new.violation_id
     and violation.status = 'pending'
     and (
       violation.subject_name = (
         select profile.full_name from public.profiles profile where profile.id = new.operator_id
       )
       or exists (
         select 1
         from public.drivers driver
         join public.operators operator_record on operator_record.id = driver.operator_id
         where driver.id = violation.driver_id
           and operator_record.user_id = new.operator_id
       )
     );

  if not found then
    raise exception 'The pending ticket is not linked to this Operator.' using errcode = '42501';
  end if;

  insert into public.notifications(title, message, type, user_id)
  select
    'City Treasurer Receipt Submitted',
    'The Operator submitted City Treasurer receipt '
      || coalesce(nullif(btrim(new.receipt_number), ''), 'for ticket ' || new.violation_id::text)
      || '. Payment may now be recorded.',
    'info',
    profile.id
  from public.profiles profile
  where profile.role in ('admin', 'staff');

  return new;
end;
$$;

revoke all on function private.process_operator_receipt_submission() from public, anon, authenticated;

drop trigger if exists process_operator_receipt_submission on public.operator_receipt_submissions;
create trigger process_operator_receipt_submission
after insert on public.operator_receipt_submissions
for each row execute function private.process_operator_receipt_submission();

create or replace function public.submit_city_treasurer_receipt(
  p_violation_id bigint,
  p_receipt_number text,
  p_storage_path text
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  insert into public.operator_receipt_submissions(
    violation_id, operator_id, receipt_number, storage_path
  ) values (
    p_violation_id, (select auth.uid()), nullif(btrim(p_receipt_number), ''), p_storage_path
  );
end;
$$;

revoke all on function public.submit_city_treasurer_receipt(bigint, text, text) from public, anon;
grant execute on function public.submit_city_treasurer_receipt(bigint, text, text) to authenticated;

notify pgrst, 'reload schema';

commit;
