-- Three-year franchise renewal workflow for Operators and TFRO Staff.

alter table public.franchises drop constraint if exists franchises_status_check;
alter table public.franchises
  add constraint franchises_status_check
  check (status in ('active', 'pending', 'expired', 'suspended', 'revoked'));

create table public.franchise_renewals (
  id bigint generated by default as identity primary key,
  operator_id uuid not null references public.profiles(id) on delete cascade,
  franchise_id bigint not null references public.franchises(id) on delete cascade,
  driver_id bigint references public.drivers(id) on delete set null,
  renewal_code text not null unique,
  renewal_type text not null check (renewal_type in ('regular', 'expired_or', 'change_motor')),
  current_expiration_date date not null,
  operator_name text not null,
  operator_address text not null,
  operator_contact text not null,
  voters_certificate_number text,
  cedula_number text,
  barangay_clearance_number text,
  driver_name text not null,
  driver_license_number text not null,
  plate_number text not null,
  engine_number text not null,
  chassis_number text not null,
  pmbl_certificate_number text,
  current_or_number text,
  current_cr_number text,
  or_registration_class text not null default 'for_hire'
    check (or_registration_class in ('for_hire', 'expired', 'private')),
  cr_registration_class text not null default 'for_hire'
    check (cr_registration_class in ('for_hire', 'private')),
  franchise_check_status text not null default 'pending'
    check (franchise_check_status in ('pending', 'up_to_date', 'expired', 'revoked')),
  status text not null default 'pending_review'
    check (status in (
      'pending_review', 'needs_correction', 'documents_verified',
      'inspection_pending', 'assessment_pending', 'awaiting_payment',
      'approved', 'rejected'
    )),
  decision_reason text,
  documents_complete boolean not null default false,
  inspection_results jsonb not null default '{}'::jsonb,
  inspection_passed boolean not null default false,
  inspection_remarks text,
  assessment_number text,
  assessment_date date,
  assessed_amount numeric(12,2) check (assessed_amount is null or assessed_amount >= 0),
  payment_status text not null default 'pending'
    check (payment_status in ('pending', 'paid')),
  payment_or_number text,
  temporary_mtop_issued boolean not null default false,
  temporary_mtop_issued_at timestamptz,
  mtop_number text,
  issuance_status text not null default 'not_ready'
    check (issuance_status in ('not_ready', 'for_printing', 'released')),
  expected_release_date date,
  new_expiration_date date,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index franchise_renewals_one_open_idx
on public.franchise_renewals (franchise_id)
where status not in ('approved', 'rejected');
create index franchise_renewals_operator_id_idx on public.franchise_renewals (operator_id);
create index franchise_renewals_driver_id_idx on public.franchise_renewals (driver_id);
create index franchise_renewals_status_idx on public.franchise_renewals (status, created_at desc);

create table public.renewal_documents (
  id bigint generated by default as identity primary key,
  renewal_id bigint not null references public.franchise_renewals(id) on delete cascade,
  doc_type text not null check (doc_type in (
    'voters_certificate', 'cedula', 'barangay_clearance', 'drivers_license',
    'picture_2x2', 'pmbl_certification', 'official_receipt',
    'certificate_registration', 'insurance'
  )),
  file_name text not null,
  storage_path text not null,
  file_size integer not null default 0 check (file_size >= 0),
  verified boolean not null default false,
  status text not null default 'pending'
    check (status in ('pending', 'verified', 'needs_correction')),
  staff_note text,
  uploaded_at timestamptz not null default now(),
  unique (renewal_id, doc_type)
);

create index renewal_documents_renewal_id_idx on public.renewal_documents (renewal_id);

alter table public.franchise_renewals enable row level security;
alter table public.franchise_renewals force row level security;
alter table public.renewal_documents enable row level security;
alter table public.renewal_documents force row level security;

revoke all on public.franchise_renewals, public.renewal_documents from anon, authenticated;
grant select, insert, update, delete on public.franchise_renewals to authenticated;
grant select, insert, update, delete on public.renewal_documents to authenticated;
grant usage, select on sequence public.franchise_renewals_id_seq to authenticated;
grant usage, select on sequence public.renewal_documents_id_seq to authenticated;

create policy "Authorized users read renewals"
on public.franchise_renewals for select to authenticated
using ((select private.is_tfro_staff()) or operator_id = (select auth.uid()));

create policy "Operators create renewals"
on public.franchise_renewals for insert to authenticated
with check (
  operator_id = (select auth.uid())
  and status = 'pending_review'
  and franchise_check_status = 'pending'
  and documents_complete = false
  and inspection_results = '{}'::jsonb
  and inspection_passed = false
  and assessed_amount is null
  and payment_status = 'pending'
  and temporary_mtop_issued = false
  and issuance_status = 'not_ready'
  and reviewed_by is null
  and reviewed_at is null
  and exists (
    select 1 from public.franchises franchise_record
    where franchise_record.id = franchise_id
      and franchise_record.operator_id = (select auth.uid())
      and franchise_record.status <> 'revoked'
  )
  and exists (
    select 1
    from public.drivers driver_record
    join public.operators operator_record on operator_record.id = driver_record.operator_id
    where driver_record.id = driver_id
      and operator_record.user_id = (select auth.uid())
  )
);

create policy "Authorized users update renewals"
on public.franchise_renewals for update to authenticated
using (
  (select private.is_tfro_staff())
  or (operator_id = (select auth.uid()) and status = 'needs_correction')
)
with check (
  (select private.is_tfro_staff())
  or (operator_id = (select auth.uid()) and status = 'pending_review')
);

create policy "Operators withdraw pending renewals"
on public.franchise_renewals for delete to authenticated
using (
  operator_id = (select auth.uid())
  and status = 'pending_review'
  and reviewed_by is null
);

create policy "Authorized users read renewal documents"
on public.renewal_documents for select to authenticated
using (
  (select private.is_tfro_staff())
  or exists (
    select 1 from public.franchise_renewals renewal
    where renewal.id = renewal_id and renewal.operator_id = (select auth.uid())
  )
);

create policy "Operators upload renewal documents"
on public.renewal_documents for insert to authenticated
with check (
  verified = false and status = 'pending' and staff_note is null
  and exists (
    select 1 from public.franchise_renewals renewal
    where renewal.id = renewal_id
      and renewal.operator_id = (select auth.uid())
      and renewal.status in ('pending_review', 'needs_correction')
  )
);

create policy "Authorized users update renewal documents"
on public.renewal_documents for update to authenticated
using (
  (select private.is_tfro_staff())
  or exists (
    select 1 from public.franchise_renewals renewal
    where renewal.id = renewal_id
      and renewal.operator_id = (select auth.uid())
      and renewal.status in ('pending_review', 'needs_correction')
  )
)
with check (
  (select private.is_tfro_staff())
  or exists (
    select 1 from public.franchise_renewals renewal
    where renewal.id = renewal_id
      and renewal.operator_id = (select auth.uid())
      and renewal.status in ('pending_review', 'needs_correction')
  )
);

create policy "Operators delete renewal documents"
on public.renewal_documents for delete to authenticated
using (
  exists (
    select 1 from public.franchise_renewals renewal
    where renewal.id = renewal_id
      and renewal.operator_id = (select auth.uid())
      and renewal.status in ('pending_review', 'needs_correction')
  )
);

create or replace function private.guard_renewal_update()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  caller_role text;
begin
  select role into caller_role from public.profiles where id = (select auth.uid());
  if caller_role = 'operator' then
    if old.operator_id <> (select auth.uid())
      or old.status <> 'needs_correction'
      or new.status <> 'pending_review'
      or new.operator_id is distinct from old.operator_id
      or new.franchise_id is distinct from old.franchise_id
      or new.driver_id is distinct from old.driver_id
      or new.renewal_type is distinct from old.renewal_type
      or new.franchise_check_status is distinct from old.franchise_check_status
      or new.documents_complete is distinct from old.documents_complete
      or new.inspection_results is distinct from old.inspection_results
      or new.inspection_passed is distinct from old.inspection_passed
      or new.assessed_amount is distinct from old.assessed_amount
      or new.payment_status is distinct from old.payment_status
      or new.temporary_mtop_issued is distinct from old.temporary_mtop_issued
      or new.issuance_status is distinct from old.issuance_status
      or new.reviewed_by is distinct from old.reviewed_by
    then
      raise exception 'Operators may only resubmit a renewal after correcting documents';
    end if;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

create trigger guard_renewal_update
before update on public.franchise_renewals
for each row execute function private.guard_renewal_update();

create or replace function private.guard_renewal_document_update()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  caller_role text;
begin
  select role into caller_role from public.profiles where id = (select auth.uid());
  if caller_role = 'operator' then
    new.verified := false;
    new.status := 'pending';
    new.staff_note := null;
    new.uploaded_at := now();
  end if;
  return new;
end;
$$;

create trigger guard_renewal_document_update
before update on public.renewal_documents
for each row execute function private.guard_renewal_document_update();

drop policy if exists "Operator upload renewal files" on storage.objects;
create policy "Operator upload renewal files"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'franchise-documents'
  and exists (
    select 1 from public.franchise_renewals renewal
    where renewal.operator_id = (select auth.uid())
      and renewal.status in ('pending_review', 'needs_correction')
      and name like 'renewals/' || renewal.id || '/%'
  )
);

drop policy if exists "Authorized users read renewal files" on storage.objects;
create policy "Authorized users read renewal files"
on storage.objects for select to authenticated
using (
  bucket_id = 'franchise-documents'
  and (
    (select private.is_tfro_staff())
    or exists (
      select 1 from public.franchise_renewals renewal
      where renewal.operator_id = (select auth.uid())
        and name like 'renewals/' || renewal.id || '/%'
    )
  )
);

drop policy if exists "Operators delete renewal files" on storage.objects;
create policy "Operators delete renewal files"
on storage.objects for delete to authenticated
using (
  bucket_id = 'franchise-documents'
  and exists (
    select 1 from public.franchise_renewals renewal
    where renewal.operator_id = (select auth.uid())
      and renewal.status in ('pending_review', 'needs_correction')
      and name like 'renewals/' || renewal.id || '/%'
  )
);

create or replace function private.notify_renewal_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  renewal_label text := coalesce(new.renewal_code, '#' || new.id);
begin
  if tg_op = 'INSERT' then
    insert into public.notifications (title, message, link, type, user_id)
    select 'New franchise renewal',
           'Franchise renewal ' || renewal_label || ' is pending TFRO review.',
           'renewals.html', 'info', profile.id
    from public.profiles profile where profile.role in ('admin', 'staff');
  elsif new.status is distinct from old.status then
    insert into public.notifications (title, message, link, type, user_id)
    values (
      'Franchise renewal update',
      case new.status
        when 'approved' then 'Your franchise renewal ' || renewal_label || ' is approved. Your MTOP is expected within 1-2 weeks.'
        when 'needs_correction' then 'Your franchise renewal ' || renewal_label || ' is not approved because requirements are incomplete: ' || coalesce(new.decision_reason, 'Please submit the missing requirements.')
        when 'rejected' then 'Your franchise renewal ' || renewal_label || ' was not approved: ' || coalesce(new.decision_reason, 'Please contact TFRO.')
        when 'awaiting_payment' then 'Your franchise renewal ' || renewal_label || ' is pending payment at the Treasurer''s Office.'
        when 'inspection_pending' then 'Documents for renewal ' || renewal_label || ' were verified. Vehicle inspection is pending.'
        else 'Your franchise renewal ' || renewal_label || ' status is now ' || replace(new.status, '_', ' ') || '.'
      end,
      'renewal.html',
      case when new.status = 'approved' then 'success'
           when new.status in ('needs_correction', 'rejected') then 'warning'
           else 'info' end,
      new.operator_id
    );

    if new.status = 'pending_review' and old.status = 'needs_correction' then
      insert into public.notifications (title, message, link, type, user_id)
      select 'Renewal requirements resubmitted',
             'Corrected requirements for renewal ' || renewal_label || ' are ready for review.',
             'renewals.html', 'info', profile.id
      from public.profiles profile where profile.role in ('admin', 'staff');
    end if;
  end if;
  return new;
end;
$$;

create trigger notify_renewal_event
after insert or update of status on public.franchise_renewals
for each row execute function private.notify_renewal_event();

create or replace function public.approve_franchise_renewal(
  p_renewal_id bigint,
  p_mtop_number text,
  p_expected_release_date date
)
returns date
language plpgsql
security invoker
set search_path = public, private, pg_temp
as $$
declare
  renewal public.franchise_renewals%rowtype;
  calculated_expiration date;
begin
  if not (select private.is_tfro_staff()) then
    raise exception 'Only TFRO Staff may approve franchise renewals';
  end if;

  select * into renewal
  from public.franchise_renewals
  where id = p_renewal_id
  for update;

  if not found then raise exception 'Renewal request was not found'; end if;
  if renewal.franchise_check_status = 'revoked' then
    raise exception 'A revoked franchise cannot be renewed';
  end if;
  if not renewal.documents_complete
    or (select count(*) from public.renewal_documents d where d.renewal_id = renewal.id and d.verified) <> 9
  then
    raise exception 'All nine renewal documents must be verified';
  end if;
  if not renewal.inspection_passed then raise exception 'Vehicle inspection must pass'; end if;
  if renewal.payment_status <> 'paid' then raise exception 'Treasurer payment must be confirmed'; end if;
  if nullif(trim(p_mtop_number), '') is null then raise exception 'MTOP number is required'; end if;

  calculated_expiration := (renewal.current_expiration_date + interval '3 years')::date;

  update public.franchises
  set status = 'active', application_type = 'renewal', application_date = current_date,
      expiration_date = calculated_expiration
  where id = renewal.franchise_id;

  update public.franchise_renewals
  set status = 'approved', decision_reason = null, mtop_number = trim(p_mtop_number),
      issuance_status = 'for_printing', expected_release_date = p_expected_release_date,
      new_expiration_date = calculated_expiration, reviewed_by = (select auth.uid()),
      reviewed_at = now(), updated_at = now()
  where id = renewal.id;

  return calculated_expiration;
end;
$$;

revoke all on function public.approve_franchise_renewal(bigint, text, date) from public, anon;
grant execute on function public.approve_franchise_renewal(bigint, text, date) to authenticated;
revoke all on function private.guard_renewal_update() from public, anon, authenticated;
revoke all on function private.guard_renewal_document_update() from public, anon, authenticated;
revoke all on function private.notify_renewal_event() from public, anon, authenticated;
