-- Keep a server-controlled record of the exact registration terms accepted.
-- The browser supplies the document versions, but this trigger validates them
-- and records the acceptance time on the server before signup can complete.
create table if not exists public.account_consents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  terms_version text not null,
  privacy_notice_version text not null,
  accepted_at timestamptz not null default now(),
  acceptance_method text not null default 'registration_checkbox',
  constraint account_consents_versions_not_blank check (
    btrim(terms_version) <> '' and btrim(privacy_notice_version) <> ''
  ),
  constraint account_consents_method_check check (
    acceptance_method in ('registration_checkbox', 'renewed_acceptance')
  ),
  constraint account_consents_user_version_unique unique (
    user_id, terms_version, privacy_notice_version
  )
);

create index if not exists account_consents_user_id_idx
  on public.account_consents(user_id);

alter table public.account_consents enable row level security;

revoke all on table public.account_consents from anon, authenticated;
revoke all on sequence public.account_consents_id_seq from anon, authenticated;
grant select on table public.account_consents to authenticated;

drop policy if exists "Users read their own consent records" on public.account_consents;
create policy "Users read their own consent records"
on public.account_consents for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Administrators read consent records" on public.account_consents;
create policy "Administrators read consent records"
on public.account_consents for select to authenticated
using ((select private.is_current_admin()));

create or replace function private.capture_registration_consent()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  expected_terms constant text := 'TFRO-TERMS-2026-09-08';
  expected_privacy constant text := 'TFRO-PRIVACY-2026-09-08';
begin
  if coalesce(new.raw_user_meta_data ->> 'terms_accepted', 'false') <> 'true'
     or coalesce(new.raw_user_meta_data ->> 'terms_version', '') <> expected_terms
     or coalesce(new.raw_user_meta_data ->> 'privacy_notice_version', '') <> expected_privacy then
    raise exception 'Terms of Use and Data Privacy Notice acceptance is required.'
      using errcode = 'P0001';
  end if;

  insert into public.account_consents (
    user_id, terms_version, privacy_notice_version, accepted_at, acceptance_method
  ) values (
    new.id, expected_terms, expected_privacy, now(), 'registration_checkbox'
  );

  return new;
end;
$$;

revoke all on function private.capture_registration_consent() from public, anon, authenticated;

drop trigger if exists capture_registration_consent_on_signup on auth.users;
create trigger capture_registration_consent_on_signup
  after insert on auth.users
  for each row execute function private.capture_registration_consent();

comment on table public.account_consents is
  'Server-recorded acceptance of versioned TFRO registration terms and privacy notices.';
